import { db, doc, writeBatch } from "../../../firebase.js";

const appId = typeof __app_id !== "undefined" ? __app_id : "default-app-id";
export const OFFICIAL_HEADERS = ["schema_version", "Id", "Nome", "Data_nascimento", "Idade", "Sexo", "chapelId", "Capela", "Bairro", "Tipo", "Estado", "Horario_estudo", "Batizado", "Primeira_eucaristia", "Crismado", "Possui_alergia_doenca", "Descricao_alergia_doenca", "Nome_mae", "Whatsapp_mae", "Nome_pai", "Whatsapp_pai", "Whatsapp_candidato", "Nome_tutor_guardiao", "Whatsapp_tutor_guardiao"];
const ESCAPE = "'";
const clean = value => String(value ?? "").trim();
const norm = value => clean(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
const encode = value => { const text = String(value ?? ""); return /^[=+\-@]/.test(text) || text.startsWith(ESCAPE) ? ESCAPE + text : text; };
const decode = value => String(value ?? "").startsWith(ESCAPE) ? String(value).slice(1) : String(value ?? "");
const cell = value => { const text = encode(value); return /[;"\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; };

/** Small RFC-4180 compatible parser for semicolon CSV, quoted fields and multiline cells. */
export function parseCsv(text) {
  const source = String(text ?? "").replace(/^\uFEFF/, ""); const rows = []; let row = [], field = "", quoted = false;
  for (let i = 0; i < source.length; i += 1) { const char = source[i];
    if (quoted) { if (char === '"' && source[i + 1] === '"') { field += '"'; i += 1; } else if (char === '"') quoted = false; else field += char; continue; }
    if (char === '"') { if (field) throw new Error("Aspas inválidas no CSV."); quoted = true; }
    else if (char === ";") { row.push(field); field = ""; }
    else if (char === "\r" || char === "\n") { if (char === "\r" && source[i + 1] === "\n") i += 1; row.push(field); rows.push(row); row = []; field = ""; }
    else field += char;
  }
  if (quoted) throw new Error("CSV com aspas não fechadas."); if (field || row.length) { row.push(field); rows.push(row); }
  return rows.filter(values => values.some(value => value !== ""));
}
export function csvToRows(text) { const rows = parseCsv(text); if (!rows.length) throw new Error("CSV vazio."); const headers = rows.shift().map(clean); return { headers, rows: rows.map((values, index) => ({ rowNumber: index + 2, values, row: Object.fromEntries(headers.map((header, i) => [header, values[i] ?? ""])) })) }; }
export function serializeOfficialCsv(servers) { return "\uFEFF" + [OFFICIAL_HEADERS.map(cell).join(";"), ...servers.map(server => OFFICIAL_HEADERS.map(header => cell(header === "schema_version" ? "1" : header === "Id" ? server.id : server[header] ?? "")).join(";"))].join("\r\n") + "\r\n"; }

const validDate = value => !value || (/^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(`${value}T00:00:00Z`).getTime()));
const validChoice = (value, choices) => !value || choices.includes(norm(value));
export function prepareOfficialImport(text, { chapels = [], existingServers = [] } = {}) {
  const { headers, rows } = csvToRows(text); const errors = [], warnings = []; const missing = OFFICIAL_HEADERS.filter(header => !headers.includes(header));
  if (missing.length) errors.push(`Colunas obrigatórias ausentes: ${missing.join(", ")}.`);
  if (headers.length !== OFFICIAL_HEADERS.length || headers.some((header, index) => header !== OFFICIAL_HEADERS[index])) errors.push("O CSV SGSA v1 deve manter exatamente as 24 colunas e a ordem oficial.");
  const ids = new Set(), chapelMap = new Map(chapels.map(chapel => [chapel.id, chapel])), existing = new Set(existingServers.map(server => server.id));
  const items = rows.map(({ rowNumber, values, row }) => { const value = key => decode(row[key] ?? ""); const id = clean(value("Id")), chapelId = clean(value("chapelId")), chapelName = clean(value("Capela"));
    if (values.length !== headers.length) errors.push(`Linha ${rowNumber}: quantidade de campos inválida.`); if (value("schema_version") !== "1") errors.push(`Linha ${rowNumber}: schema_version deve ser 1.`);
    if (!id || !clean(value("Nome")) || !chapelId || !chapelName) errors.push(`Linha ${rowNumber}: Id, Nome, chapelId e Capela são obrigatórios.`); if (id && ids.has(id)) errors.push(`Linha ${rowNumber}: Id duplicado (${id}).`); ids.add(id);
    const chapel = chapelMap.get(chapelId); if (!chapel) errors.push(`Linha ${rowNumber}: chapelId inexistente (${chapelId}).`); else if (norm(chapel.name) !== norm(chapelName)) errors.push(`Linha ${rowNumber}: Capela não corresponde ao chapelId informado.`);
    if (!validDate(value("Data_nascimento"))) errors.push(`Linha ${rowNumber}: Data_nascimento deve ser YYYY-MM-DD.`); if (!validChoice(value("Sexo"), ["masculino", "femenino", "feminino"])) errors.push(`Linha ${rowNumber}: Sexo inválido.`); if (!validChoice(value("Tipo"), ["candidato", "formando", "instituído", "instituido"])) errors.push(`Linha ${rowNumber}: Tipo inválido.`); if (!validChoice(value("Estado"), ["ativo", "inativo"])) errors.push(`Linha ${rowNumber}: Estado inválido.`);
    ["Batizado", "Primeira_eucaristia", "Crismado", "Possui_alergia_doenca"].forEach(key => { if (!validChoice(value(key), ["sim", "não", "nao"])) errors.push(`Linha ${rowNumber}: ${key} deve ser Sim, Não ou vazio.`); });
    ["Whatsapp_mae", "Whatsapp_pai", "Whatsapp_candidato", "Whatsapp_tutor_guardiao"].forEach(key => { const raw = value(key); if (raw && (!/^\d+$/.test(raw) || raw.length < 8 || raw.length > 15)) errors.push(`Linha ${rowNumber}: ${key} deve conter 8 a 15 dígitos.`); });
    const payload = Object.fromEntries(OFFICIAL_HEADERS.filter(header => !["schema_version", "Id"].includes(header)).map(header => [header, decode(row[header] ?? "")])); return { id, payload, exists: existing.has(id) };
  });
  return { official: true, items, errors, warnings, summary: { create: items.filter(item => !item.exists).length, update: items.filter(item => item.exists).length, warnings: warnings.length, errors: errors.length } };
}
export function csvToObjects(text) { const { rows } = csvToRows(text); const pick = (row, names) => row[Object.keys(row).find(key => names.includes(norm(key)))] || ""; return rows.map(({ row }) => ({ Id: pick(row,["id","identificador","codigo","código"]), Nome: pick(row,["nome","nome completo","nombre"]), Data_nascimento: pick(row,["data_nascimento","data nascimento","nascimento"]), Sexo: pick(row,["sexo","genero","gênero"]), Capela: pick(row,["capela","capilla","origem","comunidade"]), Bairro: pick(row,["bairro"]), Tipo: pick(row,["tipo","tipo de registro"]), Estado: pick(row,["estado","status","situacao","situação"]), Horario_estudo: pick(row,["horario_estudo","horário de estudo"]), Batizado: pick(row,["batizado"]), Primeira_eucaristia: pick(row,["primeira_eucaristia","primeira eucaristia"]), Crismado: pick(row,["crismado","crisma"]), Possui_alergia_doenca: pick(row,["possui_alergia_doenca","possui alergia","alergia"]), Descricao_alergia_doenca: pick(row,["descricao_alergia_doenca","descrição alergia","observacoes","observações"]), Nome_mae: pick(row,["nome_mae","nome da mae","mãe"]), Whatsapp_mae: pick(row,["whatsapp_mae","whatsapp mae","whatsapp mãe"]), Nome_pai: pick(row,["nome_pai","nome do pai"]), Whatsapp_pai: pick(row,["whatsapp_pai","whatsapp pai"]), Whatsapp_candidato: pick(row,["whatsapp_candidato","whatsapp candidato"]), Nome_tutor_guardiao: pick(row,["nome_tutor_guardiao","nome do tutor"]), Whatsapp_tutor_guardiao: pick(row,["whatsapp_tutor_guardiao","whatsapp tutor"]) })).filter(item => clean(item.Nome)); }
export async function importOfficialServers(items, progress = () => {}) { for (let start = 0; start < items.length; start += 400) { const batch = writeBatch(db); items.slice(start, start + 400).forEach(({ id, payload }) => batch.set(doc(db, "artifacts", appId, "public", "data", "servers", id), { id, ...payload }, { merge: true })); await batch.commit(); progress(Math.round(Math.min(start + 400, items.length) / items.length * 100)); } }
/** Legacy import stays intentionally tolerant; official SGSA files use importOfficialServers. */
export async function importServers(items, applyScope, progress = () => {}) { const yesNo = value => ["sim","sí","si","s","true","1","yes"].includes(norm(value)) ? "Sim" : "Não"; const state = value => ["inativo","inactivo","false","0","n","não","nao"].includes(norm(value)) ? "Inativo" : "Ativo"; const type = value => norm(value).includes("form") ? "Formando" : (norm(value).includes("inst") || norm(value).includes("serv")) ? "Instituído" : "Candidato"; const sex = value => ["femenino","feminino","f","mulher","mujer"].includes(norm(value)) ? "Femenino" : "Masculino"; for (let start = 0; start < items.length; start += 400) { const batch = writeBatch(db); items.slice(start, start + 400).forEach((item, offset) => { const id = clean(item.Id) || `SRV-${String(start + offset + 1).padStart(4, "0")}`; batch.set(doc(db, "artifacts", appId, "public", "data", "servers", id), applyScope({ id, Nome: clean(item.Nome), Data_nascimento: item.Data_nascimento || "", Sexo: sex(item.Sexo), Capela: clean(item.Capela) || "Sem Capela", Bairro: item.Bairro || "", Tipo: type(item.Tipo), Estado: state(item.Estado), Horario_estudo: item.Horario_estudo || "", Batizado: yesNo(item.Batizado), Primeira_eucaristia: yesNo(item.Primeira_eucaristia), Crismado: yesNo(item.Crismado), Possui_alergia_doenca: yesNo(item.Possui_alergia_doenca), Descricao_alergia_doenca: clean(item.Descricao_alergia_doenca), Nome_mae: clean(item.Nome_mae), Whatsapp_mae: String(item.Whatsapp_mae || "").replace(/\D/g, ""), Nome_pai: clean(item.Nome_pai), Whatsapp_pai: String(item.Whatsapp_pai || "").replace(/\D/g, ""), Whatsapp_candidato: String(item.Whatsapp_candidato || "").replace(/\D/g, ""), Nome_tutor_guardiao: clean(item.Nome_tutor_guardiao), Whatsapp_tutor_guardiao: String(item.Whatsapp_tutor_guardiao || "").replace(/\D/g, "") }), { merge: true }); }); await batch.commit(); progress(Math.round(Math.min(start + 400, items.length) / items.length * 100)); } }
