import { db, doc, writeBatch } from "../../../firebase.js";
const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';
const phone = v => (v || '').toString().replace(/\D/g, '');
const yesNo = v => ['sim','sí','si','s','true','1','yes'].includes((v||'').toString().trim().toLowerCase()) ? 'Sim' : 'Não';
const state = v => ['inativo','inactivo','false','0','n','não','nao'].includes((v||'').toString().trim().toLowerCase()) ? 'Inativo' : 'Ativo';
const type = v => { v=(v||'').toString().toLowerCase(); return v.includes('form') ? 'Formando' : (v.includes('inst') || v.includes('serv')) ? 'Instituído' : 'Candidato'; };
const sex = v => ['femenino','feminino','f','mulher','mujer'].includes((v||'').toString().trim().toLowerCase()) ? 'Femenino' : 'Masculino';
function split(line, delimiter) { let current='', quoted=false, out=[]; for (const char of line) { if(char==='"') quoted=!quoted; else if(char===delimiter && !quoted) { out.push(current); current=''; } else current+=char; } out.push(current); return out; }
export function csvToObjects(text) { if (!text?.trim()) return null; const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/); if(lines.length<2) return null; const d=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':','; const headers=split(lines[0],d).map(x=>x.trim().replace(/^"|"$/g,'')); const pick=(row,names)=>row[Object.keys(row).find(k=>names.some(n=>k.toLowerCase().replace(/[^\w]/g,'')===n.toLowerCase().replace(/[^\w]/g,'')))]||''; return lines.slice(1).map(line=>{const row={}; split(line,d).forEach((v,i)=>row[headers[i]]=v.trim().replace(/^"|"$/g,'')); return {Id:pick(row,['Id','ID','Identificador','Código']),Nome:pick(row,['Nome','Nome Completo','Nombre']),Data_nascimento:pick(row,['Data_nascimento','Data nascimento','Nascimento']),Sexo:pick(row,['Sexo','Gênero']),Capela:pick(row,['Capela','Capilla','Origem','Comunidade']),Bairro:pick(row,['Bairro']),Tipo:pick(row,['Tipo','Tipo de Registro']),Estado:pick(row,['Estado','Status','Situação']),Horario_estudo:pick(row,['Horario_estudo','Horário de estudo']),Batizado:pick(row,['Batizado']),Primeira_eucaristia:pick(row,['Primeira_eucaristia','Primeira eucaristia','1ª Comunhão']),Crismado:pick(row,['Crismado','Crisma']),Possui_alergia_doenca:pick(row,['Possui_alergia_doenca','Possui alergia','Alergia']),Descricao_alergia_doenca:pick(row,['Descricao_alergia_doenca','Descrição alergia','Observacoes']),Nome_mae:pick(row,['Nome_mae','Nome da mãe','Mãe']),Whatsapp_mae:pick(row,['Whatsapp_mae','WhatsApp mãe']),Nome_pai:pick(row,['Nome_pai','Nome do pai','Pai']),Whatsapp_pai:pick(row,['Whatsapp_pai','WhatsApp pai']),Whatsapp_candidato:pick(row,['Whatsapp_candidato','WhatsApp candidato']),Nome_tutor_guardiao:pick(row,['Nome_tutor_guardiao','Nome do tutor']),Whatsapp_tutor_guardiao:pick(row,['Whatsapp_tutor_guardiao','WhatsApp tutor'])};}).filter(item=>item.Nome?.trim()); }
export async function importServers(items, applyScope, progress) { for(let index=0;index<items.length;index+=150){const batch=writeBatch(db); items.slice(index,index+150).forEach((item,offset)=>{const id=item.Id?.trim()||`SRV-${String(index+offset+1).padStart(4,'0')}`; batch.set(doc(db,'artifacts',appId,'public','data','servers',id),applyScope({id,Nome:item.Nome.trim(),Data_nascimento:item.Data_nascimento||'',Sexo:sex(item.Sexo),Capela:(item.Capela||'Sem Capela').trim(),Bairro:item.Bairro||'',Tipo:type(item.Tipo),Estado:state(item.Estado),Horario_estudo:item.Horario_estudo||'',Batizado:yesNo(item.Batizado),Primeira_eucaristia:yesNo(item.Primeira_eucaristia),Crismado:yesNo(item.Crismado),Possui_alergia_doenca:yesNo(item.Possui_alergia_doenca),Descricao_alergia_doenca:(item.Descricao_alergia_doenca||'').trim(),Nome_mae:(item.Nome_mae||'').trim(),Whatsapp_mae:phone(item.Whatsapp_mae),Nome_pai:(item.Nome_pai||'').trim(),Whatsapp_pai:phone(item.Whatsapp_pai),Whatsapp_candidato:phone(item.Whatsapp_candidato),Nome_tutor_guardiao:(item.Nome_tutor_guardiao||'').trim(),Whatsapp_tutor_guardiao:phone(item.Whatsapp_tutor_guardiao)}),{merge:true});});await batch.commit();progress(Math.min(100,Math.round(Math.min(index+150,items.length)/items.length*100)));} }
