import { statusBadge } from "../components/status-badge.js";
import { bindBackButton, renderBackButton } from "../components/back-button.js";

function escapeHtml(value = "") { const element = document.createElement("span"); element.textContent = value; return element.innerHTML; }
function feedback(ui) { return ui.error ? `<p class="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">${escapeHtml(ui.error)}</p>` : ""; }
function dateTime(value) { const date = value?.toDate ? value.toDate() : value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleString("pt-BR") : "—"; }
function inputDateTime(value) { const date = value?.toDate ? value.toDate() : value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}T${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}` : ""; }
function statusLabel(status) { return ({ scheduled: "Agendado", in_progress: "Em andamento", completed: "Concluído", cancelled: "Cancelado" })[status] || status; }
function options(items, selected = []) { const set = new Set(selected); return items.map((item) => `<option value="${escapeHtml(item.id)}" ${set.has(item.id) ? "selected" : ""}>${escapeHtml(item.name)}</option>`).join(""); }
function list(state, actions) {
    const cards = state.data.encounters.map((encounter) => `<article class="rounded-xl border border-slate-200 bg-white p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-bold text-slate-800">${escapeHtml(encounter.title)}</h3><p class="mt-1 text-sm text-slate-600">${dateTime(encounter.startAt)}</p><p class="mt-1 text-sm text-slate-600">${escapeHtml(encounter.location?.name || "Local não informado")}</p></div>${statusBadge("encounter", encounter.status)}</div><button class="mt-4 min-h-11 w-full rounded-lg bg-slate-800 px-4 py-2 text-sm font-bold text-white sm:w-auto" data-encounter-action="details" data-encounter-id="${encounter.id}">Abrir encontro</button></article>`).join("");
    return `<section class="space-y-4">${renderBackButton()}<div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-bold">Encontros</h2><p class="text-sm text-slate-500">Grupo de formação · ${escapeHtml(state.data.currentPole?.name || "Não informado")}</p></div>${actions.canManage ? '<button class="min-h-11 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white" data-encounter-action="create">Novo encontro</button>' : ""}</div>${feedback(state.ui)}<div class="grid gap-3">${cards || '<p class="rounded-xl border border-dashed bg-white p-6 text-sm text-slate-500">Nenhum encontro cadastrado.</p>'}</div></section>`;
}
function form(state, actions) {
    const encounter = state.data.currentEncounter; const designated = (encounter?.responsibilities || []).filter((item) => item.type === "designated" && item.status === "confirmed").map((item) => item.userId);
    return `<section class="mx-auto max-w-3xl rounded-2xl border bg-white p-6"><h2 class="text-2xl font-bold">${encounter ? "Editar encontro" : "Novo encontro"}</h2>${feedback(state.ui)}<form class="mt-6 space-y-4" data-encounter-form data-encounter-id="${encounter?.id || ""}"><label class="block">Título<input required name="title" value="${escapeHtml(encounter?.title || "")}" class="mt-1 w-full rounded border p-2"></label><label class="block">Descrição<textarea name="description" class="mt-1 w-full rounded border p-2">${escapeHtml(encounter?.description || "")}</textarea></label><div class="grid gap-4 sm:grid-cols-2"><label>Início<input required type="datetime-local" name="startAt" value="${inputDateTime(encounter?.startAt)}" class="mt-1 w-full rounded border p-2"></label><label>Fim<input type="datetime-local" name="endAt" value="${inputDateTime(encounter?.endAt)}" class="mt-1 w-full rounded border p-2"></label></div><label class="block">Local<select required name="chapelId" class="mt-1 w-full rounded border p-2"><option value="">Selecione</option>${options(actions.chapels, encounter?.location?.chapelId ? [encounter.location.chapelId] : [])}</select></label><label class="block">Responsáveis designados<select multiple name="designatedIds" size="4" class="mt-1 w-full rounded border p-2" ${actions.canManageResponsibilities ? "" : "disabled"}>${options(actions.designatedCoordinators, designated)}</select>${actions.canManageResponsibilities ? "" : '<span class="mt-1 block text-xs text-slate-500">A gestão de responsáveis é exclusiva do administrador.</span>'}</label><div class="flex justify-end gap-3"><button type="button" data-encounter-action="back" class="rounded border px-4 py-2">Cancelar</button><button class="rounded bg-emerald-600 px-4 py-2 font-bold text-white">Salvar</button></div></form></section>`;
}
function statusActionLabel(status) { return ({ in_progress: "Iniciar encontro", completed: "Concluir encontro", cancelled: "Cancelar encontro" })[status] || statusLabel(status); }
function statusActionClass(status) { return status === "cancelled" ? "border border-rose-200 text-rose-700 hover:bg-rose-50" : status === "in_progress" ? "border border-sky-200 text-sky-800 hover:bg-sky-50" : "border border-slate-300 text-slate-700 hover:bg-slate-50"; }
function primaryAction(status) { return status === "scheduled" ? { label: "Iniciar encontro", action: "status", nextStatus: "in_progress" } : status === "in_progress" ? { label: "Registrar presença", action: "participants" } : status === "completed" ? { label: "Consultar presenças", action: "participants" } : null; }
function details(state, actions) {
    const e = state.data.currentEncounter;
    if (!e) return "";
    const responsibilities = (e.responsibilities || []).map((item) => `<li>${escapeHtml(actions.userNames[item.userId] || item.userId)} — ${item.type === "substitute" ? "Substituto" : "Designado"} (${item.status}) ${item.replacesUserId ? `→ ${escapeHtml(actions.userNames[item.replacesUserId] || item.replacesUserId)}` : ""}</li>`).join("");
    const primary = primaryAction(e.status);
    const secondaryActions = `<button data-encounter-action="report" class="rounded border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Ver relatório</button>${e.status === "scheduled" && actions.canManage ? '<button data-encounter-action="participants" class="min-h-11 rounded border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Gerenciar participantes</button>' : ""}${actions.canEdit ? `<button data-encounter-action="edit" data-encounter-id="${e.id}" class="rounded border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Editar</button>` : ""}${actions.canAddSubstitute ? '<button data-encounter-action="substitute" class="rounded border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Adicionar substituto</button>' : ""}`;
    const statusActions = actions.statusActions.filter((status) => status === "cancelled").map((status) => `<button data-encounter-action="status" data-encounter-status="${status}" class="min-h-11 rounded px-4 py-2 text-sm font-semibold ${statusActionClass(status)}">${statusActionLabel(status)}</button>`).join("");
    return `<section class="mx-auto max-w-3xl space-y-4">${renderBackButton()}<section class="rounded-2xl border bg-white p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="flex flex-wrap items-center gap-2"><h2 class="text-2xl font-bold">${escapeHtml(e.title)}</h2>${statusBadge("encounter", e.status)}</div><p class="mt-1 text-sm text-slate-500">${dateTime(e.startAt)} · ${escapeHtml(e.location?.name || "Local não informado")}</p></div></div>${feedback(state.ui)}${primary ? `<section class="mt-6 rounded-2xl border-2 border-emerald-200 bg-emerald-50 p-4"><p class="text-sm font-semibold text-emerald-900">Ação principal</p><button data-encounter-action="${primary.action}" data-encounter-status="${primary.nextStatus || ""}" class="mt-2 min-h-11 w-full rounded-xl bg-emerald-700 px-5 py-3 text-base font-bold text-white sm:w-auto">${primary.label}</button></section>` : ""}${e.description ? `<p class="mt-4 text-sm text-slate-700">${escapeHtml(e.description)}</p>` : ""}<section class="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 class="font-semibold text-slate-700">Detalhes administrativos</h3><div class="mt-4 border-t border-slate-200 pt-4"><h4 class="font-semibold text-slate-700">Responsáveis</h4><ul class="mt-2 list-disc pl-5 text-sm text-slate-700">${responsibilities || "<li>Nenhum responsável confirmado.</li>"}</ul></div></section>${secondaryActions ? `<div class="mt-4 flex flex-wrap gap-2">${secondaryActions}</div>` : ""}${statusActions ? `<div class="mt-4 flex flex-wrap gap-2">${statusActions}</div>` : ""}${state.navigation.currentView === "encounter-substitute" ? `<form class="mt-6 border-t pt-4" data-substitute-form><label>Responsável substituído<select required name="replacesUserId" class="mt-1 w-full rounded border p-2">${options(actions.designatedCoordinators, [])}</select></label><label class="mt-3 block">Substituto<select required name="substituteId" class="mt-1 w-full rounded border p-2">${options(actions.allCoordinators, [])}</select></label><button class="mt-3 min-h-11 rounded bg-emerald-600 px-4 py-2 text-white">Confirmar substituição</button></form>` : ""}</section></section>`;
}
function renderEncounterView(root, state, actions) { root.innerHTML = state.navigation.currentView === "encounter-form" ? form(state, actions) : state.navigation.currentView === "encounter-details" || state.navigation.currentView === "encounter-substitute" ? details(state, actions) : list(state, actions); root.querySelector("[data-encounter-form]")?.addEventListener("submit", (event) => { event.preventDefault(); const f=event.currentTarget; actions.save({ id:f.dataset.encounterId, title:f.elements.title.value, description:f.elements.description.value, startAt:f.elements.startAt.value, endAt:f.elements.endAt.value, chapelId:f.elements.chapelId.value, designatedIds:Array.from(f.elements.designatedIds.selectedOptions).map((o)=>o.value) }); }); root.querySelector("[data-substitute-form]")?.addEventListener("submit", (event)=>{event.preventDefault(); const f=event.currentTarget; actions.addSubstitute(f.elements.replacesUserId.value, f.elements.substituteId.value);}); root.querySelectorAll("[data-encounter-action]").forEach((element)=>element.addEventListener("click",()=>actions.action(element.dataset.encounterAction,element.dataset.encounterId,element.dataset.encounterStatus))); bindBackButton(root, () => actions.action("back")); }
export { renderEncounterView };
