import { statusBadge } from "../components/status-badge.js";

function escapeHtml(value = "") { const element = document.createElement("span"); element.textContent = value; return element.innerHTML; }
function feedback(ui) { return ui.error ? `<p class="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">${escapeHtml(ui.error)}</p>` : ""; }
function dateTime(value) { const date = value?.toDate ? value.toDate() : value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleString("pt-BR") : "—"; }
function inputDateTime(value) { const date = value?.toDate ? value.toDate() : value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}T${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}` : ""; }
function statusLabel(status) { return ({ scheduled: "Agendado", in_progress: "Em andamento", completed: "Concluído", cancelled: "Cancelado" })[status] || status; }
function options(items, selected = []) { const set = new Set(selected); return items.map((item) => `<option value="${escapeHtml(item.id)}" ${set.has(item.id) ? "selected" : ""}>${escapeHtml(item.name)}</option>`).join(""); }
function list(state, actions) {
    const rows = state.data.encounters.map((encounter) => `<tr class="border-t border-slate-100"><td class="whitespace-nowrap px-4 py-3 font-semibold">${escapeHtml(encounter.title)}</td><td class="whitespace-nowrap px-4 py-3">${dateTime(encounter.startAt)}</td><td class="px-4 py-3">${escapeHtml(encounter.location?.name || "—")}</td><td class="whitespace-nowrap px-4 py-3">${statusBadge("encounter", encounter.status)}</td><td class="whitespace-nowrap px-4 py-3"><button class="rounded-lg bg-slate-800 px-3 py-1.5 text-xs font-semibold text-white focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2" data-encounter-action="details" data-encounter-id="${encounter.id}">Abrir</button></td></tr>`).join("");
    return `<section class="space-y-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-bold">Encontros</h2><p class="text-sm text-slate-500">${escapeHtml(state.data.currentPole?.name || "Polo")}</p></div><div class="flex flex-wrap gap-2"><button class="rounded-lg border px-4 py-2 text-sm font-semibold" data-encounter-action="back">Voltar</button>${actions.canManage ? '<button class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white" data-encounter-action="create">Novo encontro</button>' : ""}</div></div>${feedback(state.ui)}<div class="overflow-x-auto rounded-2xl border bg-white"><table class="min-w-[700px] text-sm"><thead class="bg-slate-50 text-left"><tr><th scope="col" class="px-4 py-3">Título</th><th scope="col" class="px-4 py-3">Data</th><th scope="col" class="px-4 py-3">Local</th><th scope="col" class="px-4 py-3">Status</th><th scope="col" class="px-4 py-3">Ações</th></tr></thead><tbody>${rows || '<tr><td colspan="5" class="p-6 text-center text-slate-500">Nenhum encontro cadastrado.</td></tr>'}</tbody></table></div></section>`;
}
function form(state, actions) {
    const encounter = state.data.currentEncounter; const designated = (encounter?.responsibilities || []).filter((item) => item.type === "designated" && item.status === "confirmed").map((item) => item.userId);
    return `<section class="mx-auto max-w-3xl rounded-2xl border bg-white p-6"><h2 class="text-2xl font-bold">${encounter ? "Editar encontro" : "Novo encontro"}</h2>${feedback(state.ui)}<form class="mt-6 space-y-4" data-encounter-form data-encounter-id="${encounter?.id || ""}"><label class="block">Título<input required name="title" value="${escapeHtml(encounter?.title || "")}" class="mt-1 w-full rounded border p-2"></label><label class="block">Descrição<textarea name="description" class="mt-1 w-full rounded border p-2">${escapeHtml(encounter?.description || "")}</textarea></label><div class="grid gap-4 sm:grid-cols-2"><label>Início<input required type="datetime-local" name="startAt" value="${inputDateTime(encounter?.startAt)}" class="mt-1 w-full rounded border p-2"></label><label>Fim<input type="datetime-local" name="endAt" value="${inputDateTime(encounter?.endAt)}" class="mt-1 w-full rounded border p-2"></label></div><label class="block">Local<select required name="chapelId" class="mt-1 w-full rounded border p-2"><option value="">Selecione</option>${options(actions.chapels, encounter?.location?.chapelId ? [encounter.location.chapelId] : [])}</select></label><label class="block">Responsáveis designados<select multiple name="designatedIds" size="4" class="mt-1 w-full rounded border p-2" ${actions.canManageResponsibilities ? "" : "disabled"}>${options(actions.designatedCoordinators, designated)}</select>${actions.canManageResponsibilities ? "" : '<span class="mt-1 block text-xs text-slate-500">A gestão de responsáveis é exclusiva do administrador.</span>'}</label><div class="flex justify-end gap-3"><button type="button" data-encounter-action="back" class="rounded border px-4 py-2">Cancelar</button><button class="rounded bg-emerald-600 px-4 py-2 font-bold text-white">Salvar</button></div></form></section>`;
}
function statusActionLabel(status) { return ({ in_progress: "Iniciar encontro", completed: "Concluir encontro", cancelled: "Cancelar encontro" })[status] || statusLabel(status); }
function statusActionClass(status) { return status === "cancelled" ? "border border-rose-200 text-rose-700 hover:bg-rose-50" : status === "in_progress" ? "border border-sky-200 text-sky-800 hover:bg-sky-50" : "border border-slate-300 text-slate-700 hover:bg-slate-50"; }
function primaryAction(status) { return status === "scheduled" ? { label: "Gerenciar participantes" } : status === "in_progress" ? { label: "Registrar presença" } : status === "completed" ? { label: "Consultar presenças" } : null; }
function details(state, actions) {
    const e = state.data.currentEncounter;
    if (!e) return "";
    const responsibilities = (e.responsibilities || []).map((item) => `<li>${escapeHtml(actions.userNames[item.userId] || item.userId)} — ${item.type === "substitute" ? "Substituto" : "Designado"} (${item.status}) ${item.replacesUserId ? `→ ${escapeHtml(actions.userNames[item.replacesUserId] || item.replacesUserId)}` : ""}</li>`).join("");
    const primary = primaryAction(e.status);
    const secondaryActions = `<button data-encounter-action="report" class="rounded border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Ver relatório</button>${actions.canEdit ? `<button data-encounter-action="edit" data-encounter-id="${e.id}" class="rounded border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Editar</button>` : ""}${actions.canAddSubstitute ? '<button data-encounter-action="substitute" class="rounded border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Adicionar substituto</button>' : ""}`;
    const statusActions = actions.statusActions.map((status) => `<button data-encounter-action="status" data-encounter-status="${status}" class="rounded px-3 py-2 text-sm font-semibold ${statusActionClass(status)}">${statusActionLabel(status)}</button>`).join("");
    return `<section class="mx-auto max-w-3xl rounded-2xl border bg-white p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="flex flex-wrap items-center gap-2"><h2 class="text-2xl font-bold">${escapeHtml(e.title)}</h2>${statusBadge("encounter", e.status)}</div><p class="mt-1 text-sm text-slate-500">Detalhes do encontro</p></div><button data-encounter-action="back" class="rounded border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Voltar</button></div>${feedback(state.ui)}${e.description ? `<p class="mt-4 text-sm text-slate-700">${escapeHtml(e.description)}</p>` : ""}<section class="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><dl class="grid gap-4 text-sm sm:grid-cols-2"><div><dt class="font-semibold text-slate-500">Data e horário</dt><dd class="mt-1 text-slate-800">${dateTime(e.startAt)}</dd></div><div><dt class="font-semibold text-slate-500">Local</dt><dd class="mt-1 text-slate-800">${escapeHtml(e.location?.name || "—")}</dd></div></dl><div class="mt-4 border-t border-slate-200 pt-4"><h3 class="font-semibold text-slate-700">Responsáveis</h3><ul class="mt-2 list-disc pl-5 text-sm text-slate-700">${responsibilities || "<li>Nenhum responsável confirmado.</li>"}</ul></div></section>${primary ? `<div class="mt-6"><button data-encounter-action="participants" class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white">${primary.label}</button></div>` : ""}${secondaryActions ? `<div class="mt-4 flex flex-wrap gap-2">${secondaryActions}</div>` : ""}${statusActions ? `<section class="mt-6 border-t border-slate-200 pt-4"><h3 class="text-sm font-semibold text-slate-700">Ações de status</h3><div class="mt-3 flex flex-wrap gap-2">${statusActions}</div></section>` : ""}${state.navigation.currentView === "encounter-substitute" ? `<form class="mt-6 border-t pt-4" data-substitute-form><label>Responsável substituído<select required name="replacesUserId" class="mt-1 w-full rounded border p-2">${options(actions.designatedCoordinators, [])}</select></label><label class="mt-3 block">Substituto<select required name="substituteId" class="mt-1 w-full rounded border p-2">${options(actions.allCoordinators, [])}</select></label><button class="mt-3 rounded bg-emerald-600 px-4 py-2 text-white">Confirmar substituição</button></form>` : ""}</section>`;
}
function renderEncounterView(root, state, actions) { root.innerHTML = state.navigation.currentView === "encounter-form" ? form(state, actions) : state.navigation.currentView === "encounter-details" || state.navigation.currentView === "encounter-substitute" ? details(state, actions) : list(state, actions); root.querySelector("[data-encounter-form]")?.addEventListener("submit", (event) => { event.preventDefault(); const f=event.currentTarget; actions.save({ id:f.dataset.encounterId, title:f.elements.title.value, description:f.elements.description.value, startAt:f.elements.startAt.value, endAt:f.elements.endAt.value, chapelId:f.elements.chapelId.value, designatedIds:Array.from(f.elements.designatedIds.selectedOptions).map((o)=>o.value) }); }); root.querySelector("[data-substitute-form]")?.addEventListener("submit", (event)=>{event.preventDefault(); const f=event.currentTarget; actions.addSubstitute(f.elements.replacesUserId.value, f.elements.substituteId.value);}); root.querySelectorAll("[data-encounter-action]").forEach((element)=>element.addEventListener("click",()=>actions.action(element.dataset.encounterAction,element.dataset.encounterId,element.dataset.encounterStatus))); }
export { renderEncounterView };
