function escapeHtml(value = "") { const el = document.createElement("span"); el.textContent = value; return el.innerHTML; }
function feedback(ui) { return `${ui.error ? `<p class="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">${escapeHtml(ui.error)}</p>` : ""}${ui.success ? `<p class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">${escapeHtml(ui.success)}</p>` : ""}`; }
function statusLabel(status) { return ({ pending: "Pendente", present: "Presente", absent: "Ausente", justified: "Justificado" })[status] || "Pendente"; }
function statusClass(status) { return ({ pending: "bg-slate-100 text-slate-700", present: "bg-emerald-100 text-emerald-800", absent: "bg-rose-100 text-rose-800", justified: "bg-amber-100 text-amber-800" })[status] || "bg-slate-100 text-slate-700"; }
function attendanceControls(participant, actions, ui, encounterStatus) {
    if (!actions.canManageAttendance) return "";
    const busy = (ui.savingAttendanceIds || []).includes(participant.serverId);
    const disabled = busy ? "disabled" : "";
    const note = escapeHtml(participant.attendanceNote || "");
    const quickActions = encounterStatus === "in_progress" ? `<div class="mt-3 flex flex-wrap gap-2"><button ${disabled} class="min-h-11 rounded bg-emerald-600 px-4 py-2 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${participant.attendanceStatus === "present" ? "ring-2 ring-slate-900 ring-offset-1" : ""}" data-attendance-status="present" data-server-id="${escapeHtml(participant.serverId)}">Presente</button><button ${disabled} class="min-h-11 rounded bg-rose-600 px-4 py-2 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${participant.attendanceStatus === "absent" ? "ring-2 ring-slate-900 ring-offset-1" : ""}" data-attendance-status="absent" data-server-id="${escapeHtml(participant.serverId)}">Ausente</button><button ${disabled} class="min-h-11 rounded bg-amber-600 px-4 py-2 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${participant.attendanceStatus === "justified" ? "ring-2 ring-slate-900 ring-offset-1" : ""}" data-attendance-status="justified" data-server-id="${escapeHtml(participant.serverId)}">Justificado</button></div>` : "";
    return `<div class="mt-3">${quickActions}${busy ? '<p class="mt-2 text-xs font-medium text-slate-600">Salvando…</p>' : ""}<div class="mt-3 flex flex-wrap items-center gap-3"><details><summary class="cursor-pointer rounded text-xs font-semibold text-slate-600 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2">Nota / Corrigir</summary><form class="mt-2 w-full min-w-[18rem] rounded border bg-slate-50 p-3" data-attendance-form data-server-id="${escapeHtml(participant.serverId)}"><fieldset ${disabled}><label class="block text-xs font-semibold">Status<select name="attendanceStatus" class="mt-1 w-full rounded border bg-white p-2 text-sm"><option value="pending" ${participant.attendanceStatus === "pending" ? "selected" : ""}>Pendente</option><option value="present" ${participant.attendanceStatus === "present" ? "selected" : ""}>Presente</option><option value="absent" ${participant.attendanceStatus === "absent" ? "selected" : ""}>Ausente</option><option value="justified" ${participant.attendanceStatus === "justified" ? "selected" : ""}>Justificado</option></select></label><label class="mt-2 block text-xs font-semibold">Nota <span class="font-normal">(obrigatória para justificado)</span><textarea name="attendanceNote" maxlength="500" class="mt-1 w-full rounded border bg-white p-2 text-sm" rows="2">${note}</textarea></label><div class="mt-2"><button class="min-h-11 rounded bg-slate-800 px-4 py-2 text-xs font-semibold text-white focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2">Salvar correção</button></div></fieldset></form></details><button ${disabled} type="button" class="min-h-11 rounded border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-600 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" data-attendance-status="pending" data-server-id="${escapeHtml(participant.serverId)}">Voltar a pendente</button></div></div>`;
}
function renderParticipantsView(root, state, actions) {
    const encounterStatus = state.data.currentEncounter?.status;
    const rows = state.data.participants.map((participant) => `<tr class="border-t"><td class="whitespace-nowrap px-4 py-3 font-medium">${escapeHtml(participant.serverName)}</td><td class="px-4 py-3">${escapeHtml(participant.chapelName)}</td><td class="whitespace-nowrap px-4 py-3">${participant.participationType === "manual" ? "Manual" : "Automático"}</td><td class="px-4 py-3"><span class="inline-flex rounded-full px-2 py-1 text-xs font-semibold ${statusClass(participant.attendanceStatus)}">${statusLabel(participant.attendanceStatus)}</span>${participant.attendanceNote ? `<p class="mt-2 rounded bg-slate-50 px-2 py-1 text-xs text-slate-600">Nota: ${escapeHtml(participant.attendanceNote)}</p>` : ""}${attendanceControls(participant, actions, state.ui, encounterStatus)}</td><td class="whitespace-nowrap px-4 py-3">${actions.canManage ? `<button class="rounded border px-3 py-1 text-xs focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2" data-participant-action="remove" data-server-id="${escapeHtml(participant.serverId)}">Remover</button>` : ""}</td></tr>`).join("");
    root.innerHTML = `<section class="space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-bold">Participantes</h2><p class="text-sm text-slate-500">${escapeHtml(state.data.currentEncounter?.title || "Encontro")}</p></div><div class="flex flex-wrap gap-2"><button class="rounded border px-4 py-2" data-participant-action="back">Voltar</button>${actions.canManage ? '<button class="rounded bg-slate-800 px-4 py-2 text-white" data-participant-action="generate">Gerar participantes</button><button class="rounded bg-emerald-600 px-4 py-2 text-white" data-participant-action="manual">Adicionar participante</button>' : ""}</div></div>${feedback(state.ui)}${state.navigation.currentView === "participant-manual" ? `<form class="rounded-xl border bg-white p-4" data-manual-participant-form><label class="block text-sm font-semibold">Servidor<select required name="serverId" class="mt-1 w-full rounded border p-2"><option value="">Selecione</option>${actions.servers.map((server) => `<option value="${escapeHtml(server.id)}">${escapeHtml(server.Nome || server.id)}${server.manualWarnings?.length ? ` — ${escapeHtml(server.manualWarnings.join("; "))}` : ""}</option>`).join("")}</select></label><p class="mt-2 text-xs text-amber-700">A inclusão manual é excepcional e pode ignorar os critérios automáticos indicados em cada servidor.</p><div class="mt-3 flex gap-2"><button type="button" class="rounded border px-3 py-2" data-participant-action="back">Cancelar</button><button class="rounded bg-emerald-600 px-3 py-2 text-white">Adicionar</button></div></form>` : ""}<div class="overflow-x-auto rounded-2xl border bg-white"><table class="min-w-[820px] text-sm"><thead class="bg-slate-50 text-left"><tr><th scope="col" class="px-4 py-3">Servidor</th><th scope="col" class="px-4 py-3">Capela</th><th scope="col" class="px-4 py-3">Inclusão</th><th scope="col" class="px-4 py-3">Presença</th><th scope="col" class="px-4 py-3"><span class="sr-only">Ações</span></th></tr></thead><tbody>${rows || '<tr><td colspan="5" class="p-6 text-center text-slate-500">Nenhum participante configurado.</td></tr>'}</tbody></table></div></section>`;
    root.querySelector("[data-manual-participant-form]")?.addEventListener("submit", (event) => { event.preventDefault(); actions.addManual(event.currentTarget.elements.serverId.value); });
    root.querySelectorAll("[data-participant-action]").forEach((element) => element.addEventListener("click", () => actions.action(element.dataset.participantAction, element.dataset.serverId)));
    root.querySelectorAll("[data-attendance-status]").forEach((element) => element.addEventListener("click", () => { const attendanceStatus = element.dataset.attendanceStatus; const existingNote = state.data.participants.find((participant) => participant.serverId === element.dataset.serverId)?.attendanceNote || ""; const attendanceNote = attendanceStatus === "justified" ? window.prompt("Informe a justificativa da ausência:", existingNote) : attendanceStatus === "pending" ? "" : existingNote; if (attendanceNote !== null) actions.action("attendance", element.dataset.serverId, { attendanceStatus, attendanceNote }); }));
    root.querySelectorAll("[data-attendance-form]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const current = event.currentTarget; actions.action("attendance", current.dataset.serverId, { attendanceStatus: current.elements.attendanceStatus.value, attendanceNote: current.elements.attendanceNote.value }); }));
}
export { renderParticipantsView };
