function escapeHtml(value = "") { const el = document.createElement("span"); el.textContent = value; return el.innerHTML; }
function feedback(ui) { return `${ui.error ? `<p class="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">${escapeHtml(ui.error)}</p>` : ""}${ui.success ? `<p class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">${escapeHtml(ui.success)}</p>` : ""}`; }
function renderParticipantsView(root, state, actions) {
    const rows = state.data.participants.map((participant) => `<tr class="border-t"><td class="px-4 py-3 font-medium">${escapeHtml(participant.serverName)}</td><td class="px-4 py-3">${escapeHtml(participant.chapelName)}</td><td class="px-4 py-3">${participant.participationType === "manual" ? "Manual" : "Automático"}</td><td class="px-4 py-3">Pendente</td><td class="px-4 py-3">${actions.canManage ? `<button class="rounded border px-3 py-1 text-xs" data-participant-action="remove" data-server-id="${participant.serverId}">Remover</button>` : ""}</td></tr>`).join("");
    root.innerHTML = `<section class="space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-bold">Participantes</h2><p class="text-sm text-slate-500">${escapeHtml(state.data.currentEncounter?.title || "Encontro")}</p></div><div class="flex gap-2"><button class="rounded border px-4 py-2" data-participant-action="back">Voltar</button>${actions.canManage ? '<button class="rounded bg-slate-800 px-4 py-2 text-white" data-participant-action="generate">Gerar participantes</button><button class="rounded bg-emerald-600 px-4 py-2 text-white" data-participant-action="manual">Adicionar participante</button>' : ""}</div></div>${feedback(state.ui)}${state.navigation.currentView === "participant-manual" ? `<form class="rounded-xl border bg-white p-4" data-manual-participant-form><label class="block text-sm font-semibold">Servidor<select required name="serverId" class="mt-1 w-full rounded border p-2"><option value="">Selecione</option>${actions.servers.map((server) => `<option value="${escapeHtml(server.id)}">${escapeHtml(server.Nome || server.id)}${server.manualWarnings?.length ? ` — ${escapeHtml(server.manualWarnings.join("; "))}` : ""}</option>`).join("")}</select></label><p class="mt-2 text-xs text-amber-700">A inclusão manual é excepcional e pode ignorar os critérios automáticos indicados em cada servidor.</p><div class="mt-3 flex gap-2"><button type="button" class="rounded border px-3 py-2" data-participant-action="back">Cancelar</button><button class="rounded bg-emerald-600 px-3 py-2 text-white">Adicionar</button></div></form>` : ""}<div class="rounded-2xl border bg-white overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left"><tr><th class="px-4 py-3">Servidor</th><th class="px-4 py-3">Capela</th><th class="px-4 py-3">Inclusão</th><th class="px-4 py-3">Presença</th><th class="px-4 py-3"></th></tr></thead><tbody>${rows || '<tr><td colspan="5" class="p-6 text-center text-slate-500">Nenhum participante configurado.</td></tr>'}</tbody></table></div></section>`;
    root.querySelector("[data-manual-participant-form]")?.addEventListener("submit", (event) => { event.preventDefault(); actions.addManual(event.currentTarget.elements.serverId.value); });
    root.querySelectorAll("[data-participant-action]").forEach((element) => element.addEventListener("click", () => actions.action(element.dataset.participantAction, element.dataset.serverId)));
}
export { renderParticipantsView };
