import { bindBackButton, renderBackButton } from "../components/back-button.js";
const esc = (value = "") => { const e = document.createElement("span"); e.textContent = value; return e.innerHTML; };
const feedback = (ui) => `${ui.error ? `<p class="rounded border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">${esc(ui.error)}</p>` : ""}${ui.success ? `<p class="rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">${esc(ui.success)}</p>` : ""}`;
function members(items, actions) { return items.map((item) => `<article class="rounded-xl border bg-white p-4"><div><strong>${esc(item.serverName)}</strong><p class="mt-1 text-sm text-slate-600">${esc(item.chapelName)} · ${esc(item.serverType)}${item.age === null ? "" : ` · ${item.age} anos`}</p>${item.reasons?.length ? `<p class="mt-2 text-sm text-amber-800">${esc(item.reasons.join(" · "))}</p>` : ""}</div>${actions.canManage && item.reasons?.length ? `<button class="mt-3 min-h-11 rounded border border-rose-200 px-3 text-sm font-semibold text-rose-700" data-roster-remove="${esc(item.serverId)}">Retirar da lista</button>` : ""}</article>`).join("") || '<p class="rounded-xl border border-dashed bg-white p-5 text-sm text-slate-500">Nenhum participante preparado.</p>'; }
function renderRosterView(root, state, actions) {
 const data=actions.data; const can=actions.canManage;
 const candidates=data.candidates || [];
 root.innerHTML=`<section class="mx-auto max-w-3xl space-y-4">${renderBackButton()}<div><h2 class="text-2xl font-bold">Participantes da formação</h2><p class="text-sm text-slate-500">${esc(state.data.currentPole?.name || "Grupo de formação")}</p></div>${feedback(state.ui)}${data.legacy ? `<section class="rounded-xl border border-amber-200 bg-amber-50 p-4"><p>Esta formação ainda não possui uma lista de participantes preparada.</p>${can ? '<button data-roster-prepare class="mt-3 min-h-11 rounded bg-emerald-600 px-4 font-bold text-white">Preparar lista de participantes</button>' : ""}</section>` : ""}<div class="grid gap-3">${members(data.members || [], actions)}</div>${can ? `<section class="rounded-xl border bg-slate-50 p-4"><h3 class="font-bold">Novos servidores elegíveis</h3><p class="mt-1 text-sm text-slate-600">${candidates.length} novo(s) servidor(es) elegível(is)</p>${candidates.length ? `<button data-roster-review class="mt-3 min-h-11 rounded border px-4 font-semibold">Revisar</button><form data-roster-add class="mt-3 space-y-2 hidden"><p class="text-sm">Selecione quem deseja adicionar:</p>${candidates.map((item)=>`<label class="flex min-h-11 items-center gap-3"><input type="checkbox" name="serverIds" value="${esc(item.id)}"><span>${esc(item.Nome || item.id)} · ${esc(item.Capela || item.chapelId || "")}</span></label>`).join("")}<button class="min-h-11 rounded bg-emerald-600 px-4 font-bold text-white">Adicionar selecionados</button></form>` : ""}</section>` : ""}${can && data.review?.length ? `<section class="rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 class="font-bold">Participantes que precisam de revisão</h3><p class="mt-1 text-sm">${data.review.length} participante(s) precisam de revisão.</p></section>` : ""}</section>`;
 root.querySelector("[data-roster-review]")?.addEventListener("click",()=>root.querySelector("[data-roster-add]").classList.remove("hidden"));
 root.querySelector("[data-roster-add]")?.addEventListener("submit",(e)=>{e.preventDefault(); actions.add(Array.from(e.currentTarget.querySelectorAll('input[name="serverIds"]:checked')).map(i=>i.value));});
 root.querySelectorAll("[data-roster-remove]").forEach((b)=>b.addEventListener("click",()=>{if(confirm("Retirar este participante da lista?")) actions.remove(b.dataset.rosterRemove);}));
 root.querySelector("[data-roster-prepare]")?.addEventListener("click",actions.prepare);
 bindBackButton(root, actions.back);
}
export { renderRosterView };
