import { calculateAge, cleanStr } from "../../../utils.js";

const escapeHtml = (value = "") => { const element = document.createElement("span"); element.textContent = String(value); return element.innerHTML; };
const age = (server) => calculateAge(server?.Data_nascimento) ?? (Number.isNaN(parseInt(server?.Idade)) ? null : parseInt(server?.Idade));
const yesNo = (value) => ["sim", "si", "s"].includes(cleanStr(value)) ? "Sim" : ["nao", "não", "no", "n"].includes(cleanStr(value)) ? "Não" : "—";
const dateTime = (value) => { const date = value?.toDate ? value.toDate() : value ? new Date(value.seconds ? value.seconds * 1000 : value) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleString("pt-BR") : "Data indisponível"; };
const encounterStatus = (status) => ({ scheduled: "Agendado", in_progress: "Em andamento", completed: "Concluído", cancelled: "Cancelado" })[status] || "Contexto indisponível";
const attendance = (status) => ({ present: "Presente", absent: "Ausente", justified: "Justificado", pending: "Pendente" })[status] || "Pendente";

function currentData(server) {
  const studies = String(server?.Horario_estudo || "").split(";").map((item) => item.trim()).filter(Boolean).join(", ");
  return `<section class="rounded-2xl border border-slate-100 bg-white p-5"><h3 class="text-base font-bold text-slate-800">Dados atuais</h3><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-slate-500">Batizado</dt><dd class="font-semibold">${yesNo(server?.Batizado)}</dd></div><div><dt class="text-slate-500">Primeira eucaristia</dt><dd class="font-semibold">${yesNo(server?.Primeira_eucaristia)}</dd></div><div><dt class="text-slate-500">Crismado</dt><dd class="font-semibold">${yesNo(server?.Crismado)}</dd></div><div><dt class="text-slate-500">Horário de estudo</dt><dd class="font-semibold">${escapeHtml(studies || "—")}</dd></div></dl></section>`;
}
function metric(label, value) { return `<div class="rounded-xl bg-slate-50 p-3"><dt class="text-xs text-slate-500">${label}</dt><dd class="mt-1 text-xl font-black text-slate-800">${value}</dd></div>`; }
function historyItem(item) {
  if (!item.contextAvailable) return `<li class="rounded-xl border border-slate-200 bg-slate-50 p-4"><p class="font-semibold text-slate-700">Contexto indisponível</p><p class="mt-1 text-xs text-slate-500">O registro histórico foi preservado, mas sua formação, polo ou encontro não está mais disponível.</p></li>`;
  return `<li class="rounded-xl border border-slate-200 bg-white p-4"><div class="flex flex-wrap items-start justify-between gap-2"><div><p class="font-bold text-slate-800">${escapeHtml(item.encounter.title || "Encontro")}</p><p class="mt-1 text-sm text-slate-500">${escapeHtml(item.formation.name || "Formação")} · ${escapeHtml(item.pole.name || "Polo")}</p><p class="mt-1 text-xs text-slate-500">${dateTime(item.encounter.startAt)}</p></div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-700">${encounterStatus(item.encounter.status)}</span><span class="rounded-full bg-sky-50 px-2 py-1 text-xs font-semibold text-sky-800">${attendance(item.participant.attendanceStatus)}</span></div></div></li>`;
}
function section(title, items, empty, { visibleCount = items.length, expandable = false } = {}) { const visible = items.slice(0, visibleCount); const remaining = items.length - visible.length; return `<section class="rounded-2xl border border-slate-100 bg-white p-5"><h3 class="text-base font-bold text-slate-800">${title}</h3>${items.length ? `<ul class="mt-4 space-y-3">${visible.map(historyItem).join("")}</ul>${expandable && remaining > 0 ? `<button data-server-detail-action="more-history" class="mt-4 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Mostrar mais (${Math.min(10, remaining)} de ${remaining})</button>` : ""}` : `<p class="mt-3 text-sm text-slate-500">${empty}</p>`}</section>`; }

function renderServerDetail(root, state, actions) {
  const server = state.server;
  const history = state.history;
  const summary = history?.summary;
  const status = state.historyStatus;
  const visibleHistorical = state.visibleHistorical ?? 10;
  root.innerHTML = `<section class="mx-auto max-w-5xl space-y-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><button data-server-detail-action="back" class="mb-3 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">← Voltar</button><div class="flex flex-wrap items-center gap-2"><h2 class="text-2xl font-black text-slate-800">${escapeHtml(server?.Nome || "Servidor")}</h2><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700">${escapeHtml(server?.Estado || "Sem estado")}</span><span class="rounded-full bg-sky-50 px-2 py-1 text-xs font-bold text-sky-800">${escapeHtml(server?.Tipo || "Sem tipo")}</span></div><p class="mt-2 text-sm text-slate-500">${escapeHtml(server?.Capela || "Capela não informada")} · ${age(server) ?? "Idade não informada"}${server?.Sexo ? ` · ${escapeHtml(server.Sexo)}` : ""}</p></div><button data-server-detail-action="refresh" class="rounded-lg bg-slate-800 px-4 py-2 text-sm font-bold text-white" ${status === "loading" ? "disabled" : ""}>Atualizar histórico</button></div>${currentData(server)}<section class="rounded-2xl border border-slate-100 bg-white p-5"><h3 class="text-base font-bold text-slate-800">Trajetória em Formação</h3>${status === "loading" ? '<p class="mt-3 text-sm text-slate-500">Carregando histórico…</p>' : state.historyError ? `<p class="mt-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">Não foi possível carregar o histórico. ${escapeHtml(state.historyError)}</p>` : summary ? `<dl class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">${metric("Formações", summary.formationCount)}${metric("Encontros", summary.encounterCount)}${metric("Presentes", summary.present)}${metric("Ausentes", summary.absent)}${metric("Justificados", summary.justified)}${metric("Pendentes", summary.pending)}</dl><p class="mt-4 text-sm text-slate-600">Última participação: <strong>${summary.latestParticipation ? dateTime(summary.latestParticipation.encounter?.startAt) : "Sem presença registrada"}</strong></p>` : '<p class="mt-3 text-sm text-slate-500">Ainda não há histórico de formação para este servidor.</p>'}</section>${history ? `${section("Próximos", history.sections.upcoming, "Não há participações previstas.")}${section("Histórico", history.sections.historical, "Ainda não há participações no histórico operacional.", { visibleCount: visibleHistorical, expandable: true })}${history.sections.cancelled.length ? section("Cancelados", history.sections.cancelled, "") : ""}` : ""}</section>`;
  root.querySelectorAll("[data-server-detail-action]").forEach((element) => element.addEventListener("click", () => actions.action(element.dataset.serverDetailAction)));
}

export { renderServerDetail };
