export function renderServersWorkspace(mountElement, { isAdmin, canCreate }) {
  mountElement.innerHTML = `
    <section class="space-y-6">
      <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div><h2 class="text-2xl font-black text-slate-800">Servidores</h2><p class="text-sm text-slate-500">Cadastro, contactos e acompanhamento dos servidores.</p></div>
        <div class="flex gap-2">${isAdmin ? '<button id="servers-import-toggle" class="px-4 py-2 text-xs font-bold rounded-xl bg-slate-100 text-slate-700">Importar dados</button>' : ''}${canCreate ? '<button id="servers-add" class="px-4 py-2 text-xs font-bold rounded-xl bg-liturgical-blue text-white">+ Novo servidor</button>' : ''}</div>
      </div>
      ${isAdmin ? `<section id="servers-import-panel" class="hidden bg-white rounded-2xl p-5 border border-slate-100 space-y-3"><h3 class="font-bold text-slate-800">Importar dados CSV</h3><p class="text-xs text-slate-500">Atualiza e adiciona registros; registros ausentes no CSV são preservados.</p><input id="servers-csv-file" type="file" accept=".csv,text/csv" class="text-sm" /><div id="servers-upload-progress" class="hidden h-2 bg-slate-100 rounded"><div id="servers-upload-progress-bar" class="h-2 bg-liturgical-blue rounded" style="width:0%"></div></div></section>` : ''}
      <section class="bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden"><div class="p-6 border-b border-slate-100 space-y-4"><input id="servers-search" type="text" placeholder="Buscar por nome ou ID..." class="w-full md:w-80 px-4 py-2 text-sm bg-slate-50 border border-slate-200 rounded-xl" /><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><select id="servers-filter-chapel" class="p-2 text-xs bg-slate-50 border rounded-lg"><option value="all">Todas as capelas</option></select><select id="servers-filter-state" class="p-2 text-xs bg-slate-50 border rounded-lg"><option value="all">Todos os estados</option><option>Ativo</option><option>Inativo</option></select><select id="servers-filter-allergy" class="p-2 text-xs bg-slate-50 border rounded-lg"><option value="all">Todas as condições</option><option>Sim</option><option>Não</option></select><select id="servers-filter-type" class="p-2 text-xs bg-slate-50 border rounded-lg"><option value="all">Todos os tipos</option><option>Candidato</option><option>Formando</option><option>Instituído</option></select></div></div><div class="overflow-x-auto"><table class="w-full text-left"><thead><tr class="bg-slate-50 text-xs text-slate-500"><th class="p-4">ID / Nome</th><th class="p-4">Idade/Sexo</th><th class="p-4">Capela</th><th class="p-4">Ações</th></tr></thead><tbody id="servers-table-body"></tbody></table></div><div id="servers-empty" class="hidden p-8 text-center text-sm text-slate-500">Nenhum servidor encontrado.</div><div id="servers-pagination" class="hidden flex justify-between p-4 text-xs"><button id="servers-prev">← Anterior</button><span id="servers-page-info"></span><button id="servers-next">Próxima →</button></div></section>
    </section>`;
}
