import { createChapel, getAllChapels, countServersByChapel, normalizeChapelName, renameChapelAndSyncServers, updateChapel } from "../../data/chapels.js";
import { canManageUsers } from "../../permissions.js";

let mount = null;
let chapels = [];
let successMessage = "";
const showError = (message) => { const node = document.getElementById("error-alert-text"); if (node) node.textContent = message; document.getElementById("error-alert")?.classList.remove("hidden"); };
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));

function duplicateName(name, currentId = null) { return chapels.some((chapel) => chapel.id !== currentId && normalizeChapelName(chapel.name) === normalizeChapelName(name)); }
function render() {
  if (!mount) return;
  const search = mount.querySelector("[data-chapel-search]")?.value || "";
  const status = mount.querySelector("[data-chapel-status]")?.value || "active";
  const needle = normalizeChapelName(search);
  const list = chapels.filter((chapel) => (status === "all" || (status === "active") === (chapel.active !== false)) && (!needle || normalizeChapelName(chapel.name).includes(needle) || normalizeChapelName(chapel.address).includes(needle)));
  mount.innerHTML = `<section class="space-y-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-2xl font-black text-slate-800">Capelas</h2><p class="text-sm text-slate-500">Catálogo administrativo de capelas.</p></div><button data-chapel-new class="rounded-xl bg-liturgical-blue px-4 py-2 text-xs font-bold text-white">+ Nova capela</button></div>${successMessage ? `<p role="status" class="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">${escapeHtml(successMessage)}</p>` : ""}<section class="overflow-hidden rounded-3xl border border-slate-100 bg-white"><div class="flex flex-col gap-3 border-b p-5 sm:flex-row"><input data-chapel-search value="${escapeHtml(search)}" placeholder="Buscar por nome ou endereço..." class="w-full rounded-xl border bg-slate-50 px-4 py-2 text-sm sm:max-w-md"><select data-chapel-status class="rounded-xl border bg-slate-50 px-3 py-2 text-sm"><option value="active" ${status === "active" ? "selected" : ""}>Ativas</option><option value="inactive" ${status === "inactive" ? "selected" : ""}>Inativas</option><option value="all" ${status === "all" ? "selected" : ""}>Todas</option></select></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="p-4">Nome</th><th class="p-4">Endereço</th><th class="p-4">Estado</th><th class="p-4"></th></tr></thead><tbody>${list.map((chapel) => `<tr class="border-t text-sm text-slate-600"><td class="p-4 font-semibold">${escapeHtml(chapel.name)}</td><td class="p-4">${escapeHtml(chapel.address || "—")}</td><td class="p-4">${chapel.active !== false ? "🟢 Ativa" : "⚪ Inativa"}</td><td class="p-4 text-right"><button data-chapel-edit="${chapel.id}" class="font-bold text-liturgical-blue">Editar</button> <button data-chapel-toggle="${chapel.id}" class="ml-3 font-bold ${chapel.active !== false ? "text-amber-600" : "text-emerald-600"}">${chapel.active !== false ? "Desativar" : "Ativar"}</button></td></tr>`).join("") || '<tr><td colspan="4" class="p-8 text-center text-sm text-slate-500">Nenhuma capela encontrada.</td></tr>'}</tbody></table></div></section></section>`;
  mount.querySelector("[data-chapel-search]").addEventListener("input", render);
  mount.querySelector("[data-chapel-status]").addEventListener("change", render);
  mount.querySelector("[data-chapel-new]").addEventListener("click", () => openForm());
  mount.querySelectorAll("[data-chapel-edit]").forEach((button) => button.addEventListener("click", () => openForm(chapels.find((chapel) => chapel.id === button.dataset.chapelEdit))));
  mount.querySelectorAll("[data-chapel-toggle]").forEach((button) => button.addEventListener("click", () => toggle(chapels.find((chapel) => chapel.id === button.dataset.chapelToggle))));
}
function openForm(chapel = null) {
  const dialog = document.createElement("dialog");
  dialog.className = "rounded-2xl border p-0 shadow-xl";
  dialog.innerHTML = `<form method="dialog" class="w-[min(92vw,36rem)] space-y-4 p-6"><div><h3 class="text-xl font-bold">${chapel ? "Editar capela" : "Nova capela"}</h3><p class="mt-1 text-xs text-slate-500">Observações devem ser administrativas e não conter dados sensíveis.</p></div><label class="block text-sm">Nome<input required name="name" maxlength="120" value="${escapeHtml(chapel?.name || "")}" class="mt-1 w-full rounded border p-2"></label><label class="block text-sm">Endereço<input name="address" maxlength="250" value="${escapeHtml(chapel?.address || "")}" class="mt-1 w-full rounded border p-2"></label><label class="block text-sm">Observações<textarea name="notes" maxlength="500" class="mt-1 w-full rounded border p-2">${escapeHtml(chapel?.notes || "")}</textarea></label><label class="flex gap-2 text-sm"><input type="checkbox" name="active" ${chapel?.active !== false ? "checked" : ""}> Capela ativa</label><p data-form-error class="hidden text-sm text-rose-600"></p><div class="flex justify-end gap-3"><button value="cancel" class="rounded border px-4 py-2">Cancelar</button><button value="save" class="rounded bg-emerald-600 px-4 py-2 font-bold text-white">Salvar</button></div></form>`;
  document.body.append(dialog); dialog.showModal();
  dialog.querySelector("form").addEventListener("submit", async (event) => { if (event.submitter?.value !== "save") return; event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { name: form.get("name"), address: form.get("address"), notes: form.get("notes"), active: form.get("active") === "on" }; const error = dialog.querySelector("[data-form-error]"); if (duplicateName(payload.name, chapel?.id)) { error.textContent = "Já existe uma capela com este nome."; error.classList.remove("hidden"); return; } try { let renameResult = null; if (!chapel) await createChapel(payload); else if (normalizeChapelName(payload.name) !== normalizeChapelName(chapel.name)) { const impact = await countServersByChapel(chapel.id); const confirmed = window.confirm(`Renomear esta capela atualizará o campo Capela de ${impact} servidor(es). Registros históricos não serão alterados. Deseja continuar?`); if (!confirmed) return; renameResult = await renameChapelAndSyncServers(chapel.id, payload); } else await updateChapel(chapel.id, payload); if (renameResult) successMessage = `Capela renomeada e ${renameResult.syncedServers} servidor(es) atualizado(s).`; dialog.close(); await refresh(); } catch (err) { const progress = err.syncProgress; const chapelProgress = err.chapelUpdateProgress; error.textContent = progress ? `A sincronização foi interrompida após ${progress.completed} de ${progress.total} servidores. ${err.message}` : chapelProgress ? `${chapelProgress.completed} de ${chapelProgress.total} servidores foram atualizados, mas não foi possível concluir a atualização da capela: ${err.message}` : err.message; error.classList.remove("hidden"); } });
  dialog.addEventListener("close", () => dialog.remove());
}
function toggle(chapel) { if (!chapel) return; const action = chapel.active !== false ? "desativar" : "ativar"; document.dispatchEvent(new CustomEvent("shell:confirm", { detail: { title: `${action[0].toUpperCase()}${action.slice(1)} capela`, message: `Deseja ${action} “${chapel.name}”? Não há exclusão de dados.`, onConfirm: async () => { try { await updateChapel(chapel.id, { ...chapel, active: chapel.active === false }); await refresh(); } catch (error) { showError(`Não foi possível atualizar a capela: ${error.message}`); } } } })); }
export async function initialize({ mountElement }) { if (!canManageUsers()) return; destroy(); mount = document.createElement("div"); mount.dataset.moduleRoot = "chapels"; mountElement.append(mount); await refresh(); }
export async function refresh() { if (!mount) return; chapels = await getAllChapels(); render(); }
export function destroy() { mount?.remove(); mount = null; chapels = []; successMessage = ""; }
