import { getAllUsers, createUser, updateUser } from "../../data/users.js";
import { getAllChapels, getActiveChapels } from "../../data/chapels.js";
import { canManageUsers } from "../../permissions.js";
let mount=null, users=[];
const error=m=>{document.getElementById('error-alert-text').textContent=m;document.getElementById('error-alert').classList.remove('hidden');};
function render(){if(!mount)return;mount.innerHTML=`<section class="space-y-6"><div class="flex justify-between items-center"><div><h2 class="text-2xl font-black text-slate-800">Usuários</h2><p class="text-sm text-slate-500">Administração de acessos ao SGSA.</p></div><button id="users-new" class="px-4 py-2 text-xs font-bold rounded-xl bg-liturgical-blue text-white">+ Novo usuário</button></div><section class="bg-white rounded-3xl border overflow-hidden"><table class="w-full text-left"><thead><tr class="bg-slate-50 text-xs text-slate-500"><th class="p-4">Nome</th><th class="p-4">E-mail</th><th class="p-4">Perfil</th><th class="p-4">Capela</th><th class="p-4">Estado</th><th class="p-4"></th></tr></thead><tbody>${users.map((u,i)=>`<tr class="border-t text-sm"><td class="p-4">${u.displayName||''}</td><td class="p-4">${u.email||''}</td><td class="p-4">${u.role||''}</td><td class="p-4">${u.chapelId||'—'}</td><td class="p-4">${u.active!==false?'🟢 Ativo':'⚪ Inativo'}</td><td class="p-4">${u.uid===u.documentId?`<button data-user="${i}" class="text-liturgical-blue font-bold">Editar</button>`:'<span class="text-xs text-slate-400">Aguardando ativação</span>'}</td></tr>`).join('')||'<tr><td colspan="6" class="p-8 text-center text-slate-500">Nenhum usuário cadastrado.</td></tr>'}</tbody></table></section></section>`;document.getElementById('users-new').onclick=()=>open();mount.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>open(users[Number(b.dataset.user)]));}
async function open(item=null){if(!canManageUsers())return;const modal=document.getElementById('user-edit-modal'),form=document.getElementById('user-edit-form'),role=document.getElementById('form-user-role'),chapel=document.getElementById('form-user-chapel');document.getElementById('user-edit-modal-title').textContent=item?'Editar Usuário':'Registrar Usuário';document.getElementById('form-user-id').value=item?.uid||'';document.getElementById('form-user-display-name').value=item?.displayName||'';document.getElementById('form-user-email').value=item?.email||'';document.getElementById('form-user-email').readOnly=!!item;role.value=item?.role||'viewer';document.getElementById('form-user-active').value=item?.active!==false?'true':'false';chapel.innerHTML='';const [active,all]=await Promise.all([getActiveChapels(),getAllChapels()]);active.sort((a,b)=>a.name.localeCompare(b.name)).forEach(c=>chapel.add(new Option(c.name,c.id)));const historical=all.find(c=>c.id===item?.chapelId&&c.active===false);if(historical){const option=new Option(`${historical.name} (inativa)`,historical.id);option.disabled=true;chapel.add(option);}chapel.value=item?.chapelId||'';const sync=()=>{chapel.disabled=role.value==='admin';if(chapel.disabled)chapel.value='';};role.onchange=sync;sync();form.onsubmit=async e=>{e.preventDefault();const email=document.getElementById('form-user-email').value.trim(),chapelId=chapel.value,userData={displayName:document.getElementById('form-user-display-name').value.trim(),role:role.value,chapelId:role.value==='admin'?null:chapelId,active:document.getElementById('form-user-active').value==='true'};if((role.value==='coordinator'||role.value==='viewer')&&!chapelId)return error('Selecione uma capela.');try{if(item)await updateUser(item.uid,userData);else await createUser({id:email,email,...userData});modal.classList.add('hidden');await refresh()}catch(err){error('Não foi possível guardar o usuário: '+err.message)}};modal.classList.remove('hidden');}
export async function initialize({mountElement}){if(!canManageUsers())return;mount=document.createElement('div');mount.dataset.moduleRoot='users';mountElement.append(mount);await refresh();document.getElementById('btn-cancel-user-edit').onclick=()=>document.getElementById('user-edit-modal').classList.add('hidden');}
export async function refresh(){if(!mount)return;users=await getAllUsers();render();}
export function destroy(){document.getElementById('user-edit-modal')?.classList.add('hidden');const form=document.getElementById('user-edit-form');if(form)form.onsubmit=null;mount?.remove();mount=null;users=[];}
